component = require("component")
file = io.open("map.txt","a")
print("Introduce IPV4 ?.x.x.x MAX:")
max1 = io.read()
print("Introduce IPV4 ?.x.x.x MIN:")
min1 = io.read()
print("Introduce IPV4 x.?.x.x MAX:")
max2 = io.read()
print("Introduce IPV4 x.?.x.x MIN:")
min2 = io.read()
print("Introduce IPV4 x.x.?.x MAX:")
max3 = io.read()
print("Introduce IPV4 x.x.?.x MIN:")
min3 = io.read()
print("Introduce IPV4 x.x.x.? MAX:")
max4 = io.read()
print("Introduce IPV4 x.x.x.? MIN:")
min4 = io.read()
print("Introduce address destino:")
addr = io.read()
comp = component.get(addr)
print("Introduce nodo final?:")
fin = io.read()
file:write("\n"..max1..","..min1..","..max2..","..min2..","..max3..","..min3..","..max4..","..min4..","..comp..","..fin)
file:close()
print("Operacion exitosa! :)")